### ISSUE TITLE
Job hangs when run on cluster with 0 workers

### ISSUE THREAD

**Issue by ammarar** [Eventual-Inc/Daft#1823]
**Describe the bug**
When a Daft job that is run on a Ray cluster that has 0 workers (with autoscaling enabled) and with a head node with `num-cpus: "0"`, it hangs on `write_parquet(`.

**To Reproduce**
1. Create a Ray cluster that has the following characteristics (attached):

    a. 0 workers, but with autoscaling
    ```yaml
    additionalWorkerGroups:
      smallGroup:
        disabled: false
        replicas: 0
        minReplicas: 0
        maxReplicas: 5
    ```
    b. Head does not schedule any jobs by setting `num-cpus`
    ```yaml
    rayStartParams:
      # You can also set {"num-cpus": "0"} in "rayStartParams" of "headGroupSpec" such that Ray scheduler
      # will skip the head node when scheduling workloads.
      # This also helps to maintain the stability of the head.
      num-cpus: '0'
    ```
2. Run a job that reads and writes to blob store (attached).

**Expected behavior**
The job is expected to run to completion similar to if it was to run with 1 worker.

**Actual behavior**
The job hangs on `df.write_parquet(` and does not finish.

**Versions (please complete the following information):**
 - Ray: 2.9
 - KubeRay: 1.0.0
 - Daft: 0.2.12

**Additional context**
None
[issue_files.zip](https://github.com/Eventual-Inc/Daft/files/14087776/issue_files.zip)
