### ISSUE TITLE
Failed to install getdaft[dashboard]

### ISSUE THREAD

**Issue by hongbo-miao** [Eventual-Inc/Daft#3886]
### Describe the bug

I saw 

> UserWarning: Unable to import Daft's dashboard featuresConsider re-installing Daft with the 'dashboard' feature installed, e.g.:pip install "getdaft[dashboard]"

many times. So I am curious what this dashboard provides. I cannot find any document about it.

Anyway, I want to give a try. However, I met issue installing `getdaft[dashboard]` using [uv](https://github.com/astral-sh/uv).

### To Reproduce

pyproject.toml:

```toml
[project]
name = "my-project"
version = "1.0.0"
requires-python = "~=3.13.0"
dependencies = [
  "httpx==0.28.1",
  "getdaft[dashboard]==0.4.6",
]

[tool.uv]
package = false
```

`uv sync` gives me error

```sh
  × No solution found when resolving dependencies:
  ╰─▶ Because daft-dashboard was not found in the package registry and getdaft[dashboard]==0.4.6 depends on daft-dashboard, we can conclude that getdaft[dashboard]==0.4.6 cannot be used.
      And because your project depends on getdaft[dashboard]==0.4.6, we can conclude that your project's requirements are unsatisfiable.
```

Tried Python 3.13, 3.12, 3.11, all shows same error.

Seems it tries to install a library `daft-dashboard` which does not exist https://pypi.org/search/?q=daft-dashboard

### Expected behavior

Expecting no error.

### Component(s)

Other
